// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/account-information" | "/address-book" | "/admin" | "/admin/analytics" | "/admin/categories" | "/admin/coupons" | "/admin/orders" | "/admin/products" | "/admin/settings" | "/admin/users" | "/admin/vendors" | "/bespoke" | "/blog" | "/blog/[slug]" | "/cart" | "/checkout" | "/contact" | "/contact-us" | "/home" | "/login" | "/my-orders" | "/newsletter-subscriptions" | "/privacy" | "/privacy-policy" | "/product-reviews" | "/product/[id]" | "/profile" | "/refund-and-cancellation-policy" | "/shipping" | "/shipping-and-delivery-policy" | "/shop" | "/shop/[...segments]" | "/social-accounts" | "/terms-and-conditions" | "/vendor" | "/vendor/orders" | "/vendor/products" | "/vendor/settings" | "/wishlist"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = "/api/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/account-information": {}
  "/address-book": {}
  "/admin": {}
  "/admin/analytics": {}
  "/admin/categories": {}
  "/admin/coupons": {}
  "/admin/orders": {}
  "/admin/products": {}
  "/admin/settings": {}
  "/admin/users": {}
  "/admin/vendors": {}
  "/api/[[...path]]": { "path"?: string[]; }
  "/bespoke": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/cart": {}
  "/checkout": {}
  "/contact": {}
  "/contact-us": {}
  "/home": {}
  "/login": {}
  "/my-orders": {}
  "/newsletter-subscriptions": {}
  "/privacy": {}
  "/privacy-policy": {}
  "/product-reviews": {}
  "/product/[id]": { "id": string; }
  "/profile": {}
  "/refund-and-cancellation-policy": {}
  "/shipping": {}
  "/shipping-and-delivery-policy": {}
  "/shop": {}
  "/shop/[...segments]": { "segments": string[]; }
  "/social-accounts": {}
  "/terms-and-conditions": {}
  "/vendor": {}
  "/vendor/orders": {}
  "/vendor/products": {}
  "/vendor/settings": {}
  "/wishlist": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
